# Generated by Django 6.0.2 on 2026-03-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='iin',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
