# Generated by Django 6.0.2 on 2026-03-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='iin',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
