# Generated by Django 6.0.2 on 2026-03-09 21:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.StreamField([('rtfblock', 0), ('imgblock', 1), ('embedblock', 2), ('button', 5)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'ol', 'ul', 'hr', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'bold', 'italic', 'link'], 'label': 'Текст'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'template': 'blocks/image_block.html'}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Youtube', 'template': 'blocks/embed_block.html'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Button text', 'required': True}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Link', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('url', 4)]], {})}),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='body',
            field=wagtail.fields.StreamField([('rtfblock', 0), ('imgblock', 1), ('embedblock', 2), ('button', 5)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'ol', 'ul', 'hr', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'bold', 'italic', 'link'], 'label': 'Текст'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'template': 'blocks/image_block.html'}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Youtube', 'template': 'blocks/embed_block.html'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Button text', 'required': True}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Link', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('url', 4)]], {})}),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='body',
            field=wagtail.fields.StreamField([('rtfblock', 0), ('imgblock', 1), ('embedblock', 2), ('button', 5)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'ol', 'ul', 'hr', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'bold', 'italic', 'link'], 'label': 'Текст'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'template': 'blocks/image_block.html'}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Youtube', 'template': 'blocks/embed_block.html'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Button text', 'required': True}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Link', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('url', 4)]], {})}),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.fields.StreamField([('rtfblock', 0), ('imgblock', 1), ('embedblock', 2), ('button', 5)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'ol', 'ul', 'hr', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'bold', 'italic', 'link'], 'label': 'Текст'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'template': 'blocks/image_block.html'}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Youtube', 'template': 'blocks/embed_block.html'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Button text', 'required': True}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Link', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('url', 4)]], {})}),
        ),
        migrations.AlterField(
            model_name='podcastpage',
            name='body',
            field=wagtail.fields.StreamField([('rtfblock', 0), ('imgblock', 1), ('embedblock', 2), ('button', 5)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'ol', 'ul', 'hr', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'bold', 'italic', 'link'], 'label': 'Текст'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'template': 'blocks/image_block.html'}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Youtube', 'template': 'blocks/embed_block.html'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Button text', 'required': True}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Link', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('url', 4)]], {})}),
        ),
    ]
