# Generated by Django 6.0.2 on 2026-03-25 19:15

from django.db import migrations

def copy_participants(apps, schema_editor):
    EventPage = apps.get_model("home", "EventPage")
    EventParticipant = apps.get_model("home", "EventParticipant")

    for event in EventPage.objects.all():
        for user in event.participants.all():
            EventParticipant.objects.get_or_create(
                event=event,
                user=user
            )

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_eventpage_participants_eventparticipant'),
    ]

    operations = [
        migrations.RunPython(copy_participants),
    ]
