# Generated by Django 6.0.2 on 2026-03-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20260325_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpage',
            old_name='participants',
            new_name='participants_old',
        ),
    ]
