# Generated by Django 6.0.2 on 2026-03-25 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_participants_eventpage_participants_old'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events', through='home.EventParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='participants_old',
            field=models.ManyToManyField(blank=True, related_name='events_old', to=settings.AUTH_USER_MODEL),
        ),
    ]
